// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sophrosync.Reporting.Infrastructure.Persistence;

#nullable disable

namespace Sophrosync.Reporting.Infrastructure.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sophrosync.Reporting.Domain.Entities.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Type", "IsActive");

                    b.ToTable("report_definitions", (string)null);
                });

            modelBuilder.Entity("Sophrosync.Reporting.Domain.Entities.ReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReportDefinitionId", "Status");

                    b.ToTable("report_runs", (string)null);
                });

            modelBuilder.Entity("Sophrosync.Reporting.Domain.Entities.ReportDefinition", b =>
                {
                    b.OwnsOne("Sophrosync.Reporting.Domain.ValueObjects.ReportSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ReportDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("schedule_day_of_week");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("schedule_is_active");

                            b1.Property<TimeOnly?>("TimeOfDay")
                                .HasColumnType("time without time zone")
                                .HasColumnName("schedule_time_of_day");

                            b1.HasKey("ReportDefinitionId");

                            b1.ToTable("report_definitions");

                            b1.WithOwner()
                                .HasForeignKey("ReportDefinitionId");
                        });

                    b.Navigation("Schedule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
